version: '3.5'

services:
  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: ./
      dockerfile: backend/Dockerfile
    volumes:
      - /home/jorman/DPIA/images:/home/images
    command: [python, backend.py]

  ui:
    container_name: interface
    image: interface:1.0.0
    build:
      context: ./
      dockerfile: interface/Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/jorman/DPIA/images:/home/images
    environment:
    #  - DISPLAY=127.0.0.1:0
      - DISPLAY=unix$DISPLAY
    command: [python, interface.py]